language: node_js
sudo: false
node_js:
  - "node"
  - "lts/*"
before_install:
  - "[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest"
  - npm install -g greenkeeper-lockfile@2
install:
  - npm install
before_script:
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
cache:
  directories:
    - "$HOME/.npm"
