/* eslint-disable max-len, max-statements */

import write from './write';

/**
 * generate package.json
 * @param {String} name project name
 * @param {String} dest destination path
 * @param {OPTIONS} options command line options
 * @return {Promise}
 */
export default async function generatePackageJson(name = '', dest = '', options = {}) {
  if (typeof name !== 'string') {
    throw new TypeError('Argument "name" is not string.');
  }
  if (typeof dest !== 'string') {
    throw new TypeError('Argument "dest" is not string.');
  }

  const devDependencies = [
          {name: '@babel/core', version: '^7.0.0'},
          {name: '@babel/preset-env', version: '^7.0.0'},
          {name: '@babel/register', version: '^7.0.0'},
          {name: '@hidoo/eslint-config', version: '^0.1.2'},
          {name: '@hidoo/util-fancy-print', version: '^0.0.0'},
          {name: 'babel-eslint', version: '^9.0.0'},
          {name: 'commander', version: '^2.17.1'},
          {name: 'cross-env', version: '^5.2.0'},
          {name: 'eslint', version: '^5.6.0'},
          {name: 'gulp', version: '^4.0.0'},
          {name: 'husky', version: '^1.0.0-rc.14'},
          {name: 'lint-staged', version: '^7.2.2'},
          {name: 'npm-run-all', version: '^4.1.3'},
          {name: 'rimraf', version: '^2.6.2'}
        ],
        scripts = [
          {name: 'start', command: 'npm run dev'},
          {name: 'dev', command: 'cross-env NODE_ENV=development gulp'},
          {name: 'dev:build', command: 'cross-env NODE_ENV=development npm-run-all -s static:clean static:build'},
          {name: 'prod', command: 'cross-env NODE_ENV=production gulp'},
          {name: 'prod:build', command: 'cross-env NODE_ENV=production npm-run-all -s static:clean static:build'},
          {name: 'static:clean', command: 'gulp clean'},
          {name: 'static:build', command: 'gulp build'},
          {name: 'static:watch', command: 'gulp watch'},
          {name: 'test', command: 'npm-run-all -s test:*'},
          {name: 'test:lint', command: 'eslint .'}
        ],
        {verbose} = options;

  if (options.css) {
    devDependencies.push(
      {name: '@hidoo/gulp-task-build-css-stylus', version: '^0.0.0'}
    );
  }
  if (options.cssDeps) {
    devDependencies.push(
      {name: '@hidoo/gulp-task-concat', version: '^0.0.0'}
    );
  }
  if (options.html) {
    devDependencies.push(
      {name: '@hidoo/gulp-task-build-html-handlebars', version: '^0.0.0'}
    );
  }
  if (options.image) {
    devDependencies.push(
      {name: '@hidoo/gulp-task-optimize-image', version: '^0.0.0'}
    );
  }
  if (options.js) {
    devDependencies.push(
      {name: '@babel/polyfill', version: '^7.0.0'},
      {name: 'babel-preset-power-assert', version: '^3.0.0'},
      {name: 'jsdom', version: '^12.0.0'},
      {name: 'jsdom-global', version: '^3.0.2'},
      {name: 'mocha', version: '^5.2.0'},
      {name: 'power-assert', version: '^1.6.0'}
    );
    scripts.push(
      {name: 'test:unit', command: 'cross-env NODE_ENV=test mocha ./src/js/**/*.test.js --opts ./src/js/mocha.opts'}
    );
    switch (options.jsBundler) {
      case 'browserify':
        devDependencies.push(
          {name: '@hidoo/gulp-task-build-js-browserify', version: '^0.0.0'}
        );
        break;
      case 'rollup':
        devDependencies.push(
          {name: '@hidoo/gulp-task-build-js-rollup', version: '^0.0.0'}
        );
        break;
      default:
    }
  }
  if (options.jsDeps) {
    devDependencies.push(
      {name: '@hidoo/gulp-task-concat', version: '^0.0.0'}
    );
  }
  if (options.server) {
    devDependencies.push(
      {name: '@hidoo/express-engine-handlebars', version: '^0.0.0'},
      {name: '@hidoo/util-local-ip', version: '^0.0.0'},
      {name: 'browser-sync', version: '^2.24.7'},
      {name: 'express', version: '^4.16.3'}
    );
  }
  if (options.sprite) {
    switch (options.spriteType) {
      case 'svg':
        devDependencies.push(
          {name: '@hidoo/gulp-task-build-sprite-svg', version: '^0.0.0'}
        );
        break;
      case 'image':
        devDependencies.push(
          {name: '@hidoo/gulp-task-build-sprite-image', version: '^0.0.0'}
        );
        break;
      default:
    }
  }
  if (options.styleguide) {
    devDependencies.push(
      {name: '@hidoo/gulp-task-build-styleguide-kss', version: '^0.0.0'},
      {name: '@hidoo/gulp-task-copy', version: '^0.0.0'}
    );
  }

  const json = {
    name: name,
    version: '0.0.0',
    description: `${name} project. (Generated by @hidoo/gulp-project-generator)`,
    private: true,
    author: '',
    main: 'gulpfile.babel.js',
    engines: {
      node: '>=8.0.0',
      npm: '>=5.0.0'
    },
    scripts: scripts
      .sort((a, b) => a.name.localeCompare(b.name))
      .reduce((prev, current) => ({...prev, [current.name]: current.command}), {}),
    devDependencies: devDependencies
      .sort((a, b) => a.name.localeCompare(b.name))
      .reduce((prev, current) => ({...prev, [current.name]: current.version}), {}),
    dependencies: {},
    husky: {
      hooks: {
        'pre-commit': 'lint-staged'
      }
    },
    'lint-staged': {
      '**/*.js': [
        'eslint'
      ]
    }
  };

  try {
    await write(JSON.stringify(json, null, '  '), `${dest}/package.json`, {verbose});
  }
  catch (error) {
    throw error;
  }
}
