name: Test

on:
  - push
  - pull_request

jobs:
  test:
    name: "Test on Node.js ${{ matrix.node-version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x
          - 18.x
          - 20.x
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Enable corepack
        run: corepack enable yarn
      - name: Install dependencies
        run: yarn
      - name: Setup packages
        run: yarn bootstrap
      - name: Run tests
        run: yarn test
